In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

import numpy as np

In [2]:
df =pd.DataFrame(np.arange(0,20).reshape(5,4), index=['row1','row2','row3','row4','row5'], columns=['column1','column2','column3','column4'])

In [3]:
df.head()

      column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [4]:
df.to_csv('test1.csv')

In [5]:
df.loc['row1']

column1    0
column2    1
column3    2
column4    3
Name: row1, dtype: int64

In [6]:
df['column1']

row1     0
row2     4
row3     8
row4    12
row5    16
Name: column1, dtype: int64

In [7]:
df.iloc[:,1:]

      column2  column3  column4
row1        1        2        3
row2        5        6        7
row3        9       10       11
row4       13       14       15
row5       17       18       19

In [8]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [9]:
df['column1'].value_counts

<bound method IndexOpsMixin.value_counts of row1     0
row2     4
row3     8
row4    12
row5    16
Name: column1, dtype: int64>

In [10]:
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [11]:
df = pd.read_csv("US_E-commerce_records_2020.csv",encoding='windows-1252')

In [12]:
df.head()

,Order Date,Row ID,Order ID,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,01-01-20,849,CA-2017-107503,Standard Class,GA-14725,Consumer,United States,Lorain,Ohio,44052,East,FUR-FU-10003878,Furniture,Furnishings,"Linden 10"" Round Wall Clock, Black",48.896,4,0.2,8.5568
1,01-01-20,4010,CA-2017-144463,Standard Class,SC-20725,Consumer,United States,Los Angeles,California,90036,West,FUR-FU-10001215,Furniture,Furnishings,"Howard Miller 11-1/2"" Diameter Brentwood Wall ...",474.430,11,0.0,199.2606
2,01-01-20,6683,CA-2017-154466,First Class,DP-13390,Home Office,United States,Franklin,Wisconsin,53132,Central,OFF-BI-10002012,Office Supplies,Binders,Wilson Jones Easy Flow II Sheet Lifters,3.600,2,0.0,1.7280
3,01-01-20,8070,CA-2017-151750,Standard Class,JM-15250,Consumer,United States,Huntsville,Texas,77340,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,454.560,5,0.2,-107.9580
4,01-01-20,8071,CA-2017-151750,Standard Class,JM-15250,Consumer,United States,Huntsville,Texas,77340,Central,FUR-FU-10002116,Furniture,Furnishings,"Tenex Carpeted, Granite-Look or Clear Contempo...",141.420,5,0.6,-187.3815

In [13]:
#give the info about the column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3312 entries, 0 to 3311
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order Date    3312 non-null   object
 1   Row ID        3312 non-null   int64
 2   Order ID      3312 non-null   object
 3   Ship Mode     3312 non-null   object
 4   Customer ID   3312 non-null   object
 5   Segment       3312 non-null   object
 6   Country       3312 non-null   object
 7   City          3312 non-null   object
 8   State         3312 non-null   object
 9   Postal Code   3312 non-null   int64
 10  Region        3312 non-null   object
 11  Product ID    3312 non-null   object
 12  Category      3312 non-null   object
 13  Sub-Category  3312 non-null   object
 14  Product Name  3312 non-null   object
 15  Sales         3312 non-null   float64
 16  Quantity      3312 non-null   int64
 17  Discount      3312 non-null   float64
 18  Profit        3312 non-null   float64
dtypes: float64(3), int64(3), object(13)
memory usage: 491.8+ KB

In [14]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,3312.000000,3312.000000,3312.000000,3312.000000,3312.000000,3312.000000
mean,5087.107488,56186.515097,221.381418,3.766908,0.156467,28.212340
std,2817.482266,31980.375516,585.257531,2.221776,0.207429,241.864342
min,13.000000,1841.000000,0.444000,1.000000,0.000000,-3839.990400
25%,2655.750000,27978.750000,17.018000,2.000000,0.000000,1.763200
50%,5183.500000,60472.500000,53.810000,3.000000,0.200000,8.296800
75%,7498.250000,90032.000000,205.105700,5.000000,0.200000,28.315125
max,9994.000000,99301.000000,13999.960000,14.000000,0.800000,6719.980800

In [15]:
df["Ship Mode"].value_counts()

Ship Mode
Standard Class    1897
Second Class       657
First Class        572
Same Day           186
Name: count, dtype: int64

In [16]:
df["Country"].value_counts()

Country
United States    3312
Name: count, dtype: int64

In [17]:
df1 = pd.read_csv("US_E-commerce_records_2020.csv",encoding='windows-1252',usecols=['Quantity','Sales','Profit'])

In [18]:
df1.head()

     Sales  Quantity    Profit
0   48.896         4    8.5568
1  474.430        11  199.2606
2    3.600         2    1.7280
3  454.560         5 -107.9580
4  141.420         5 -187.3815

In [19]:
df['Quantity'][2]

np.int64(2)

In [20]:
#gives output from the main data
df['Sales'][3]

np.float64(454.56)

In [21]:
from io import StringIO

data=('a,b,c\n'
        '1,2,3\n'
        '4,5,6\n')
print(data)

a,b,c
1,2,3
4,5,6

In [22]:
pd.read_csv(StringIO(data))

   a  b  c
0  1  2  3
1  4  5  6

In [23]:
#read json to csv
data={"employee_name":"sanvi","email_id":"js@gmail.com","job_profile":"IT"}
df1=pd.DataFrame(data, index=[0])
print(df1)

  employee_name      email_id job_profile
0         sanvi  js@gmail.com          IT

In [24]:
df1.to_json()

'{"employee_name":{"0":"sanvi"},"email_id":{"0":"js@gmail.com"},"job_profile":{"0":"IT"}}'

In [25]:
df1.to_json(orient="records")

'[{"employee_name":"sanvi","email_id":"js@gmail.com","job_profile":"IT"}]'

In [26]:
df1.to_csv("job_csv")